image:
  file: .gitpod/.gitpod.Dockerfile

tasks:
  - name: Run PetClinic app
    init: ./mvnw clean install -U -DskipTests
    command: |
      (cd .gitpod
        wget https://raw.githubusercontent.com/meysholdt/shared-folder-sample-lib/main/.gitpod/link_m2.sh
        wget https://raw.githubusercontent.com/meysholdt/shared-folder-sample-lib/main/.gitpod/mount_shared_folder.sh
        chmod +x link_m2.sh
        chmod +x mount_shared_folder.sh
      )
      export PATH="$PATH:$GITPOD_REPO_ROOT/.gitpod"
      gp idp login aws --role-arn arn:aws:iam::950174689815:role/shared-state-access-role
      mount_shared_folder.sh
      link_m2.sh

      ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
