image:
  file: .gitpod/.gitpod.Dockerfile

tasks:
  - name: Run PetClinic app
    init: ./mvnw clean install -U -DskipTests
    command: |
      # authenticate with AWS via OIDC so we can get access to S3
      gp idp login aws --role-arn arn:aws:iam::950174689815:role/shared-state-access-role

      # mount our S3 bucket to a local folder
      mount_s3.sh shared-state-test /workspace/shared-folder-sample-lib/shared

      # use a symlink to relocate the Maven artifact into the shared folder
      link.sh secretsauce /workspace/m2-repository/com/mycompany /workspace/shared-folder-sample-lib/shared

      # run application
      ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
